// <auto-generated />
namespace TaskManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TaskDetailsPropertyAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskDetailsPropertyAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202310230742220_TaskDetailsPropertyAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
